### ISSUE TITLE
Special characters in file path could cause problems

### ISSUE THREAD

**Issue by Provissy** [master-of-zen/Av1an#39]
Sorry, hit [ENTER] key accidentally...

When special characters (like Japanese) are present in input path, this error will be instantaneously reported.

`Error in PySceneDetectOpenCV VideoCapture object failed to return True when calling isOpened().`

OS: Windows 10 19H2
Release: 1.0.175 from AppVeyor Artifact.

**Comment by master-of-zen** [comment]
Will look what can be done about that

**Comment by master-of-zen** [comment]
Can you give me example of name that  gives error?

**Comment by Provissy** [comment]
> Can you give me example of name that gives error?

Sure! For example.

`PS R:\_Tools> .\av1an.exe -i "R:\メディア AOM AV1\ビデオ_2019-05-23-13-21-25.mp4" -o out.mkv`

Gives

`Error in PySceneDetectOpenCV VideoCapture object failed to return True when calling isOpened().`

I also found that if the path contains `space`, the encoding process might eventually failed in some steps. Maybe the `space` is recognised as a parameter separator?

**Comment by Provissy** [comment]
Could you please also tell me or document that what does the outputted frame rate mean. Does it indicate frame rate **per worker** or  **cumulated**? Thank you very much! I really enjoy your work.

**Comment by master-of-zen** [comment]
Spaces in paths, and filenames should work fine. I addressed this issue a while ago.
Frame Rate that is showed in progress bar is **cumulative** fps of encoded chunks.

**Comment by master-of-zen** [comment]
What i found is that:
1. This file name is fine and should work.![](https://cdn.discordapp.com/attachments/670992383860539392/693567474171641937/Screenshot_2020-03-28_22-09-15.png)
2. `Error in PySceneDetectOpenCV VideoCapture object failed to return True when calling isOpened().` Appears when ffmpeg module within PySceneDetect is failing to find codec to open video stream. Adding required FFMPEG video codec is on OpenCv devs.

Simplest solution is to convert video stream to lossless x264/x265

**Comment by master-of-zen** [comment]
@Provissy is issue still preserve? If not or no reply - I will close issue tomorrow

**Comment by Provissy** [comment]
Sorry for delayed reply...

Back to days ago when you replied okay, the problem still persist. I tried today with your shiny new release, now it's gone!

Thank you very much for solving it.

There is a extra minor problem, `pip3 install Av1an` won't install `libsm` which is required but not installed by default on a Ubuntu Server. Exception is threw when importing `cv2`. Could probably add a note in README.md?

**Comment by master-of-zen** [comment]
:+1:
