### ISSUE TITLE
Does nothing 

### ISSUE THREAD

**Issue by lynrayy** [master-of-zen/Av1an#676]
Program just does nothing after command
![image](https://user-images.githubusercontent.com/59417884/196609244-e35d7ebd-14b5-415f-a8eb-bbb8666b4bfd.png)

**Comment by menditsa** [comment]
No need to put the path for the current folder.
Just put the file after -i

**Comment by lynrayy** [comment]
Still nothing (even no errors)
![image](https://user-images.githubusercontent.com/59417884/196618704-92df46a7-769b-4704-bce0-bd9fc1121694.png)

**Comment by silverbacknet** [comment]
Something weird is happening, I wonder if it's silently crashing or something. That would show in the event log. Try with --verbose to see how far it gets.

**Comment by FreezyLemon** [comment]
IIRC, this (av1an doing nothing) happens when it has problems locating the required libraries, usually FFmpeg. It's possible that a more recent av1an build wants a newer FFmpeg version than 0.3.1. Check your event viewer, it might have more info.

**Comment by muizzsiddique** [comment]
Av1an would show a pop-up if it is missing any of FFmpeg 4 and 5's DLLs (you need both in my experience). 

Have you tried ".\av1an.exe ..." in case it is somehow running the wrong executable?

**Comment by tgurath** [comment]
This problem still exists in the latest nightly build.

If the ffmpeg dlls are missing you do, indeed, get pop up error dialogs outside the console window informing you of each missing dll.

Like others, I dumped everything into a single directory for easy nuking if it doesn't work or if I don't decide to keep it. av1an, vapoursynth, ffmpeg dlls, SvtAv1EncApp exe and dll.

Running av1an.exe with or without any params, including `-h`, `--help` and `-i test.mkv` all result in being returned to the prompt after ~2 seconds.

An error does appear in the Windows event log.

```- System 

  - Provider 

   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
 
   EventID 1000 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2022-12-15T05:13:59.6653131Z 
 
   EventRecordID 12464 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  29100 
   [ ThreadID]  28208 
 
   Channel Application 
 
   Computer Legion 
 
  - Security 

   [ UserID]  S-1-5-21-3076471134-1816865337-2510947463-1001 
 

- EventData 

  AppName av1an.exe 
  AppVersion 0.0.0.0 
  AppTimeStamp 638f790f 
  ModuleName unknown 
  ModuleVersion 0.0.0.0 
  ModuleTimeStamp 00000000 
  ExceptionCode c0000005 
  FaultingOffset 0000000000000000 
  ProcessId 0x6160 
  ProcessCreationTime 0x1d9104409df0fd2 
  AppPath C:\Users\[redacted]\Downloads\VapourSynth64-Portable-R61\av1an.exe 
  ModulePath unknown 
  IntegratorReportId 3106353f-e350-4754-9993-8e0d2de12765 
  PackageFullName  
  PackageRelativeAppId  
```
For my initial tests I ran via Docker on Windows with WSL2. Encoding is significantly slower that way than running the encoders natively. It's not a viable alternative for heavy use.

**Comment by dexeonify** [comment]
Try reinstalling Python and Vapoursynth. I've encountered this issue before, and there are virtually no useful logs/errors messages to help troubleshoot it. The crash gets logged in Windows' Event Viewer, but of course it didn't provide any meaningful information. Turns out that my Python install is wonky, which in turn broke my Vapoursynth install. Also, I see you are using Vapoursynth Portable, perhaps try the executable version?

**Comment by tgurath** [comment]
> crash gets logged in Windows' Event Viewer, but of course it didn't provide any meaningful information

Yes, I noticed it was meaningless but I copied it anyway to put to rest any doubts as to whether there was an actual crash.

> Try reinstalling Python

Thanks. This pointed me in the right direction. I had the latest python, which vapoursynth doesn't support yet. Swapping that out resolved the problem.

**Comment by tehCh0nG** [comment]
> Thanks. This pointed me in the right direction. I had the latest python, which vapoursynth doesn't support yet. Swapping that out resolved the problem.

Do you know which versions of python and vapoursynth fixed the issue? I'm having the same problem. I tried using several Python versions (3.10.x) and Vapoursynth R60 and R61.

**Comment by tgurath** [comment]
> Do you know which versions of python and vapoursynth fixed the issue? I'm having the same problem. I tried using several Python versions (3.10.x) and Vapoursynth R60 and R61.

I've got Vapoursynth R60. I originally used Python 3.11 64-bit. After the discussion here I checked Vapoursynth's docs and used the latest 3.10 version. I then ran `vs-detect-python.bat` as mentioned in the Windows Installation (Portable) section of the docs. http://www.vapoursynth.com/doc/installation.html#windows-installation-portable. av1an worked for me at that point.

**Comment by silverbacknet** [comment]
VS is very tied to Python internals, but the 3.10 version should work with any 3.10.x. Both should be either portable or All Users installed. There could also be a bad plugin being loaded, or a plugin that has a dependency that isn't being found; perhaps empty out the plugins folder and try running VS alone; if that works, add them back until one fails. (Av1an will require many of the plugins, so that's not a permanent solution.)

You might be interested in this tool: https://github.com/tdebaets/wertweak It will make silent crashes visible for troubleshooting this kind of problem.

**Comment by tehCh0nG** [comment]
Thank you, silverbacknet and tgurath for the assistance! av1an is working now. I was able to resolve it via the following:
1) Download Python-3.10.9 embeddable, VapourSynth R61 portable, and av1an (of course).
2) Extract all files to the same directory.
3) Run `vs-detect-python.bat`.

**Comment by jriker1** [comment]
I download av1an.exe in Windows and copied over the requested DLL's and it runs and sits and comes back with a blank screen.  From reading above yes it's showing event log errors:

Faulting application name: av1an.exe, version: 0.0.0.0, time stamp: 0x640f0b27
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x3c84
Faulting application start time: 0x01d9576acc3a9519
Faulting application path: D:\temp\av1an\av1an.exe
Faulting module path: unknown
Report Id: a8487952-c421-42aa-b852-43f093213918
Faulting package full name: 
Faulting package-relative application ID:

**Comment by menditsa** [comment]
it needs avdevice-59.dll for now as well as avdevice-60.dll

**Comment by jriker1** [comment]
Here is what I did in case it helps anyone.  I try to avoid physical installs at all costs:

Downloaded and placed the following in a folder call av1an:

- Python embedded latest version
- VapourSynth64-portable latest available 
- Av1an.exe
- Encoder exe of your choice

Run "vs-detect-python.bat".

Av1an should now work correctly.

Additionally copied the following into the av1an folder: 

- Copy ffms2.dll to vapoursynth plugin folder
- Copy libvslsmashsource.dll to vapoursynth plugin folder

**Comment by he852100** [comment]
Currently, it is true that the file still does not prompt, such as Python xxx. dll. If the Python command line is missing, no results will be returned
The windows store version of python will not find python, you need to use a non-store version or a portable version
